--Data Analysis

--Total number of returns
select count(total_amt)[Returns] from Transactions
where total_amt < 0

--Average age of customers
select  avg(DATEDIFF(YEAR,DOB,GETDATE()))[Avg_age] from Customer


--Number of transaction per store type
select Store_type, count(transaction_id)[Num_transaction] from Transactions
group by Store_type
order by  count(transaction_id) desc

--Nmber of male and female in the data
select Gender, count(customer_Id) [Count] from Customer
where Gender in ('M','F')
group by Gender

--City wise distribution of customers
select city_code,count(customer_Id)[Total_Customers] from Customer
group by city_code
order by count(customer_Id) desc



--Net revenue generated from books and electronics
select t1.prod_cat_code, t2.prod_cat, sum(t1.total_amt)[TotalRevenue] from Transactions t1 inner join prod_cat_info t2 on t2.prod_cat_code=t1.prod_cat_code and t1.prod_subcat_code=t2.prod_sub_cat_code
where t2.prod_cat in ('Electronics','Books')
group by t2.prod_cat , t1.prod_cat_code

--Number of Customers with more than 10 transaction exculding returns 
select count(cust_id) [Count of customers] from
 (select cust_id,count(cust_id) [Trans] from Transactions
 where total_amt > 0
 group by cust_id
 having count(cust_id) > 10) t1

--Percentage of sales and returns by product sub cat 	
select  t1.prod_subcat_code,t1.Sales,t2.[Returns] from (select prod_subcat_code,sum(total_amt)/ (select sum(total_amt) from Transactions)[Sales] from Transactions
 group by prod_subcat_code) t1 inner join  (select prod_subcat_code, abs(sum(total_amt)/ (select sum(total_amt) from Transactions
 where total_amt < 0)) [Returns] from Transactions
 group by prod_subcat_code) t2 on t1.prod_subcat_code=t2.prod_subcat_code

 
 --Total revenue generated by consumers aged between 25 and 30 in last in the last 30 days of transction 
 select sum(total_amt) from Transactions
 where tran_date >= (select DATEADD(DAY,-30,max(tran_date)) from Transactions) and cust_id in  (select customer_Id from Customer
 where DATEDIFF(YEAR,DOB,GETDATE()) between 25 and 35)


-- Quantity and sales of different store type
select  Store_type, sum(total_amt) [SalesAmt] ,sum(Qty) [Qty] from Transactions
group by Store_type


--Categories with average revenue above the overall revenue
select prod_cat_code, avg(total_amt) from Transactions
group by prod_cat_code
having avg(total_amt) > (select avg(total_amt) from Transactions)

--Year on year growth in sales
select year(tran_date) [Year],sum(total_amt)/lag(sum(total_amt),1) over (order by year(tran_date))[YOY Growth] from Transactions
group by  year(tran_date)

--Total amount per customer per year orderd by total amount per customer
select cust_id,year(tran_date)[Year],sum(total_amt)[Total_amt] from Transactions
group by cust_id , year(tran_date)
order by cust_id,rank() over (partition by cust_id order by sum(total_amt) desc)

-- Running total of total amount on a montly basis
with cte1 as
(select year(tran_date)[Year],month(tran_date)[Month],sum(total_amt)[Total_amt] from Transactions
group by  year(tran_date),month(tran_date))
select *,sum(Total_amt) over (order by [year] , [month])[Running_total] from cte1
order by [year] , [month]



